services:
  - type: web
    name: kushicosultancy
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: production
